[global]
_output_dir = "~/q8020"
_inject_outdir = "-outdir"
_env = "./fvm_euler_1d_solver/.venv"
_script = "python ./fvm_euler_1d_solver/nozzle_1d_solver.py"


[fvm_1d_nelem_2]
"-linsolver" = "HHL"
"-backend" = "fake fake_guadalupe"
"-nelem" = 2
"-localdt" = true
"-noshow" = true
"-shots" = 1024
"-iters" = 4
"-initers" = 1


